# Markdown
This is a markdown cell where we write instructions and math formulas. **Double click** to edit and **press Run** to see the formatted texts.

# Load and Save Notebook
To load a note book, just go to "File" and navigate to "Open...". Use keyboard shortcut **Cmd/Ctrl+s** to save the file. You will be saving a checkpoint as well if you use this keyboard shortcut. You can click on "File" on the menu bar and select an option to revert to a certain checkpoint. Jupyter Notebook will also autosave your file every 120s, but it's still a good practice to press **Cmd/Ctrl+s** often when you write programs. 

# Code Blocks
Below will be an example of a Python code block. Hit **Run** to run the block.

In [1]:
print("Hello world!")

Hello world!


You can also hit **Run All** in "Cell" menu. To run every blocks. 

In [2]:
print("Hello world, again!")

Hello world, again!


# Python Programming
We have finished Jupyter Notebook introduction. Below we will start Python Programming.

## Importing Libraries
For the lab, we will be using different libraries. This is how you do it in Python.

In [2]:
import pandas as pd
import numpy as np

By importing pandas as pd, you can use the shorthand `pd` when you need to use pandas. The same method applies to `np`.

## NumPy Tutorial
Below we show you a few ways to create arrays.

In [11]:
# Create a basic array
x = np.array([0, 1, 2, 3])
print("x:\n", x)

# Create a 2D array
y = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])
print("y:\n", y)

# Create a 3 by 4 empty array
z = np.zeros((3, 4))
print("z:\n", z)

# Create a 5 by 5 array filled with 1s
a = np.ones((5, 5))
print("a:\n", a)

# Create a sequence of numbers, note the array does not include 20
b = np.arange(0, 20, 2)
print("b:\n", b)

# Use reshape to change the dimention of the array
c = np.arange(0, 20, 2, dtype=float).reshape(2, 5)
print("c:\n", c)

# Create a random 6 by 3 array with value between [0, 1).
d = np.random.rand(6, 3)
print("d:\n", d)
    
    # This creates random values ranging between [1, 4).
d = d*3 + 1
print("New d:\n", d)

# Operations
e = d + 10
print("e:\n", e)

x:
 [0 1 2 3]
y:
 [[0 1 2 3]
 [4 5 6 7]]
z:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
a:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
b:
 [ 0  2  4  6  8 10 12 14 16 18]
c:
 [[ 0.  2.  4.  6.  8.]
 [10. 12. 14. 16. 18.]]
d:
 [[0.75294125 0.80976605 0.08401273]
 [0.71902851 0.90460423 0.26972981]
 [0.81065987 0.35478825 0.2815138 ]
 [0.70371863 0.96402214 0.87457595]
 [0.49285049 0.73951861 0.69251929]
 [0.82293464 0.67770141 0.41918165]]
New d:
 [[3.25882376 3.42929816 1.2520382 ]
 [3.15708554 3.71381269 1.80918942]
 [3.43197961 2.06436476 1.84454139]
 [3.1111559  3.89206641 3.62372784]
 [2.47855147 3.21855582 3.07755788]
 [3.46880391 3.03310422 2.25754494]]
e:
 [[13.25882376 13.42929816 11.2520382 ]
 [13.15708554 13.71381269 11.80918942]
 [13.43197961 12.06436476 11.84454139]
 [13.1111559  13.89206641 13.62372784]
 [12.47855147 13.21855582 13.07755788]
 [13.46880391 13.03310422 12.25754494]]


**Now it's your turn.** 

**To-do:**
1. Create and print out an empty array with dimensions of 15 by 29.
2. From the 0 array you created, make it to an ones array without using np.ones. Print out the array.
3. Create an 8 by 9 array with values between $[5, 11)$. Note that 11 is excluded. Print out the array.



In [7]:
### Insert code below ###


a = np.zeros((15,29))
print(a + 1)

b = np.random.rand(8,9) * 6 + 5
print(b)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1

## Pandas Tutorial
### Create Data Frame
Pandas is a data frame that will be used to handel our data.

In [12]:
# Create a data frame from numpy array
df_1 = pd.DataFrame(y, columns=['col 1', 'col 2', 'col 3', 'col 4'])
print("df_1:\n", df_1, '\n')
print("------------------------------------") # for readability only

# You can also use display() to make the dataframe looks nicer at the output
print("df_1 using display:")
display(df_1)
print("------------------------------------")

# Create a data frame with strings
data_2 = {'Aminal': ['Dog', 'Cat'], 'Color': ['Yellow', 'Pink'], 'Age': [1, 3]}
df_2 = pd.DataFrame(data=data_2)
print("df_2:\n", df_2, '\n')
print("------------------------------------")

# Print the type of the data. Notice that Age is int
df_2.dtypes

df_1:
    col 1  col 2  col 3  col 4
0      0      1      2      3
1      4      5      6      7 

------------------------------------
df_1 using display:


col 1  col 2  col 3  col 4
0      0      1      2      3
1      4      5      6      7

------------------------------------
df_2:
   Aminal   Color  Age
0    Dog  Yellow    1
1    Cat    Pink    3 

------------------------------------


Aminal    object
Color     object
Age        int64
dtype: object

#### Now it's your turn. 

**To-do:**

1. Create a data frame containing demographics of you and your 2 friends. The data frame should be 3 by 4. The columns will be 'Name', 'Age', 'Height', 'Hobby'. You can make up data if you like. Print or display the result. 

In [22]:
### Insert your code below ###
data = np.array([['Anuraag', 23, 72, 'Hiking'], ['Mamata', 26, 62, 'Netflix'], ['Ramesh', 60,  60, 'Biking']])
demographics = pd.DataFrame(data, columns = ['Name', 'Age', 'Height', 'Hobby'])
demographics


Name Age Height    Hobby
0  Anuraag  23     72   Hiking
1   Mamata  26     62  Netflix
2   Ramesh  60     60   Biking

### Modify Data Frame
Notice that when you use `=`, you are not copying data frame. You are just saying that `df_3` is now referring to the same data frame as `df_1`. If you change values in `df_3` you will change the values in `df_1` too, since both are referring to the same dataframe. Also notice that every time you click **Run** in this block, the values in `'col 1'` changes.  

In [16]:
# Add a new column
df_2['Weight'] = [89, 60]
print("New df_2:")
display(df_2)
print("------------------------------------")

# Special thing to take notice
df_3 = df_1
df_3['col 1'] = df_3['col 1'] - 1
print("df_3:")
display(df_3)
print("df_1:")
display(df_1)


New df_2:


Aminal   Color  Age  Weight
0    Dog  Yellow    1      89
1    Cat    Pink    3      60

------------------------------------
df_3:


col 1  col 2  col 3  col 4
0     -4      1      2      3
1      0      5      6      7

df_1:


col 1  col 2  col 3  col 4
0     -4      1      2      3
1      0      5      6      7

### Print Specific Data
Here we use `.loc`, `.at` to obtain the cell values by providing the **labels** (e.g. 'Age', 'Weight'). For rows, since we do not create labels for them the defaults will be 0, 1, 2, 3...etc. We use `.iloc`, `.iat` to obtain the cell values by prividing the indicies (positions) of the rows and columns. 

In [17]:
# Few ways to view the values

# Create a data frame based on data_2; the values are copied
df_4 = pd.DataFrame(data=data_2)
print("df_4:")
display(df_4)
print("------------------------------------")

# Selection by Label
    # Getting the scalar value
dog_age = df_4.loc[0, 'Age']
print("Age of Dog:", dog_age, '\n')
print("------------------------------------")

    # Getting the whole column 
aminals_age = df_4.loc[:, ['Age']]
print("Age Column:")
display(aminals_age)
print("------------------------------------")

    # Faster way to get a scalar
cat_age = df_4.at[1, 'Age']
print("Age of Cat:", cat_age, '\n')
print("------------------------------------")

# Selection by position
    # Selecting Row based on row number
dog = df_4.iloc[0]
print("Dog row:")
print(dog, '\n')
print("------------------------------------")

    # Selecting Col based on col number
animals_age_p = df_4.iloc[:, 2]
print("Animals' age:")
print(animals_age_p, '\n')
print("------------------------------------")
    # Selecting cell based on col number
cat_age_p = df_4.iat[1, 2]
print("Age of Cat: ", cat_age_p)

df_4:


Aminal   Color  Age
0    Dog  Yellow    1
1    Cat    Pink    3

------------------------------------
Age of Dog: 1 

------------------------------------
Age Column:


Age
0    1
1    3

------------------------------------
Age of Cat: 3 

------------------------------------
Dog row:
Aminal       Dog
Color     Yellow
Age            1
Name: 0, dtype: object 

------------------------------------
Animals' age:
0    1
1    3
Name: Age, dtype: int64 

------------------------------------
Age of Cat:  3


#### Now it's your turn.
**To-do:**

1. Add a new **row** to your **demographics** data frame. The new row will contain information of another friend. *Note that we haven't taught you how to do so but you should be able to find resources online easily.* Print/display the data frame.
2. Print all the information (whole row) about you using `.loc`.
3. Print the 'Name' of your second friend using `.iat`.


In [38]:
### Insert your code below ###
new_row = {'Name': 'Mala', 'Age': 52, 'Height': 60, 'Hobby': 'Walking'}
# demographics.append(new_row, ignore_index=True)
print('My info:\n', demographics.loc[0], '\n')
print('2nd friend:\n', demographics.iat[2, 0])

My info:
 Name      Anuraag
Age            23
Height         72
Hobby      Hiking
Name: 0, dtype: object 

2nd friend:
 Ramesh


**Congradulation on finishing the tutorial! Now you can move on to the next step of the lab.**